def texto_comandos():
    return (
        "📜 **Comandos disponibles:**\n\n"
        "🎬 $startanime \"Nombre\" @sugeridor @usuario_n\n"
        "👥 $unirse Nombre\n"
        "🔍 $verinfo Nombre\n"
        "⏩ $avanzar <capitulo> Nombre\n"
        "📋 $lista\n"
        "📊 $votar Nombre\n"
        "🏆 $popular\n"
        "✏️ $renombrar \"Nombre actual\" \"Nombre nuevo\"\n"
        "🏷️ $alias \"Nombre\" \"alias1\" \"alias2\" ...\n"
        "✅ $visto \"Nombre\"\n"
        "❌ $eliminaranime \"Nombre\"\n"
        "⏳ $progreso Nombre\n"
        "❓ $guia Comando\n"
        "⬇️ $dropear Nombre \n"
        "📤 $dropeados\n"
        "🔄 $desdropear Nombre\n"
        "📦 $infobot\n"
        "⚙️ $actualizar Nombre\n"
        "🏓 $ping\n"
        "🤫 $secreto\n"
        "🏅 $logros @usuario\n"
        "♻️ $relanzar\n"
        "💡 Prefijos: $"
    )